name: mercado_pago
description: Mercado Pago Helper
version: 0.0.6
author: Brian Salvattore <briansalvattore@gmail.com>
homepage: https://github.com/briansalvattore/mercado_pago_flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: